version: 0.0
os: linux
files:
  - source: /examples/helloworld/greeter_server/greeter_server
    destination: /home/ubuntu/grpc-go/examples/helloworld/greeter_server
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

